name: Pulse Dylib Compiler
on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Lua
        run: curl -L http://www.lua.org/ftp/lua-5.1.4.tar.gz | tar xz

      - name: Build Pulse Dylib
        run: |
          cd lua-5.1.4/src
          # Διαγράφουμε τα αρχεία που προκαλούν το error
          rm -f lua.c luac.c loslib.c
          # Σχολιάζουμε το loslib reference στο linit.c
          sed -i '' 's/{LUA_OSLIBNAME, luaopen_os},/\/\/ {LUA_OSLIBNAME, luaopen_os},/' linit.c
          # Κάνουμε compile τα υπόλοιπα αρχεία για iOS
          clang -arch arm64 -isysroot $(xcrun --sdk iphoneos --show-sdk-path) \
          -miphoneos-version-min=14.0 -dynamiclib -o Pulse.dylib *.c

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Pulse-Dylib
          path: lua-5.1.4/src/Pulse.dylib
